FROM langflowai/langflow:latest
ENV LANGFLOW_HOST=0.0.0.0
ENV LANGFLOW_PORT=10000
ENV PORT=10000
ENV LANGFLOW_NUM_WORKERS=1
ENV DO_NOT_TRACK=true
ENV LANGFLOW_AUTO_LOGIN=true
EXPOSE 10000
CMD ["langflow", "run", "--backend-only"]
